In [1]:
import numpy as np
import pandas as pd

In [2]:
filename = 'data/melon_song_v2.csv'
plist_filename1 = 'data/melon_playlist1.csv'
plist_filename2 = 'data/melon_playlist2_v2.csv'

In [3]:
df = pd.read_csv(filename)
plist1 = pd.read_csv(plist_filename1)
plist2 = pd.read_csv(plist_filename2)
df.shape, plist1.shape, plist2.shape

((6247, 14), (3845, 5), (60271, 4))

In [9]:
df[df.plylstSeq.isna()][['songId']]

        songId
211   35831252
234   35725437
251   36401603
302   36377460
316     170666
...        ...
6137  34620822
6143  34620840
6148   3515505
6149   3515511
6151   4072537

[121 rows x 1 columns]

In [4]:
df.date.fillna(0, inplace=True)
df.date = df.date.astype(int).astype(str)
df.songId = df.songId.astype(str)
df.fillna('', inplace=True)
df.lyric = df.lyric.str.replace('\r', '')
df.head()

,songId,title,artist,genre,album,lyricist,composer,date,img,comment,like,lyric,plylstSeq,total
0,418168,희재,성시경,발라드 국내영화,국화꽃 향기 OST,양재선,MGR,20030201,https://cdnimg.melon.co.kr/cm/album/images/000...,332,138267,햇살은 우릴 위해 내리고 \n바람도 서롤 감싸게 했죠 \n우리 웃음속에 계절은 오고...,445029956 411111859,햇살 우릴 위해 내리다 바람 서 롤 감싸다 하다 우리 웃음 속 계절 오다 또 가다 ...
1,35609035,인생은 뷰티풀,김호중,발라드 국내영화,인생은 뷰티풀: 비타돌체,김호중,김호중,20220907,https://cdnimg.melon.co.kr/cm2/album/images/11...,197,17322,하나만 알고 둘은\n잘 모르는 사람입니다\n하루는 비틀거리고\n하루는 뒤뚱거리고\n...,457536944 474137187,하나 만 고 둘 자다 모르다 사람 이다 하루 비틀 거리 고 하루 뒤뚱거리 고 월요일...
2,1046278,서쪽 하늘,이승철,발라드 국내영화,청연 OST,이승철,윤명선,20051220,https://cdnimg.melon.co.kr/cm/album/images/003...,84,48109,서쪽하늘로 노을은 지고 \n이젠 슬픔이 돼버린 그대를 \n다시 부를수 없을 것 ...,426571097 405285190,서쪽하늘 노을 지고 젠 슬픔 돼다 버리다 그대 다시 부르다 없다 같다 또 한번 불다...
3,35609034,슬픈등,김호중,발라드 국내영화,인생은 뷰티풀: 비타돌체,김호중,김호중,20220907,https://cdnimg.melon.co.kr/cm2/album/images/11...,145,15389,누군가를 다시 만난다면\n여전히 나는 너를\n누군가를 다시 사랑하면\n영원히 나는 ...,457536944 515278519,누군가 다시 만나다 여전하다 나 너 누군가 다시 사랑 하다 영원하다 나 너 다시 또...
4,35728845,고백 (영화 '동감' X 츄 (이달의 소녀)),츄(Chuu),록/메탈 국내영화,고백 (영화 '동감' X 츄 (이달의 소녀)),강현민,강현민,20221016,https://cdnimg.melon.co.kr/cm2/album/images/11...,80,16902,말해야 하는데 네 앞에 서면\n아무 말 못 하는 내가 미워져\n용기를 내야 해 후회...,484732185 513801514,말 하다 하다 네 앞 서면 아무 말 못 하다 내 가 미우다 용기 내야 해 후회 하다...

In [9]:
df.isna().sum()

songId         0
title          0
artist         0
genre          2
album          0
lyricist     398
composer     402
date           0
img            0
comment        0
like           0
lyric          5
plylstSeq    121
dtype: int64

In [ ]:
for val in df.genre.unique():
    print(val)

In [27]:
# 장르별 노래 총합
df.pivot_table('songId', 'genre', aggfunc='count').sort_values('songId', ascending=False).head(10)

             songId
genre
발라드             957
성인가요/트로트        819
댄스              692
랩/힙합            473
국내뮤지컬           472
록/메탈            467
R&B/Soul        458
발라드 국내드라마       350
포크/블루스          295
인디음악 포크/블루스     275

In [32]:
# 발매년도별 노래 총합
df['year'] = df.date.str[:4]

In [33]:

df.pivot_table('songId', 'year', aggfunc='count').sort_values('songId', ascending=False).head(10)

      songId
year
2023     677
2022     648
2021     464
2020     394
2019     334
2017     240
2018     234
2016     228
2010     153
2015     150

In [34]:
df.columns

Index(['songId', 'title', 'artist', 'genre', 'album', 'lyricist', 'composer',
       'date', 'img', 'comment', 'like', 'lyric', 'plylstSeq', 'year'],
      dtype='object')

In [ ]:
plist1.songIds

In [50]:
# songId 별로 playlist 에 들어있는 개수
df['p_count'] = df.songId.apply(lambda x : len(plist1[plist1.songIds.str.contains(str(x))]))

In [62]:
# playlist에 가장 많이 들어가 있는 곡은? 
df.sort_values('p_count', ascending=False)[['songId', 'title', 'artist', 'genre', 'comment', 'like', 'year', 'p_count']].head(20)

,songId,title,artist,genre,comment,like,year,p_count
1100,9390,Doc와 춤을,DJ DOC,댄스,44,14328,2000,144
1775,3743,그런 일은,박화요비,R&B/Soul,195,58243,2000,117
1275,7712,당신은 모르실거야 (CF - LIG 핑클편),핑클 (Fin.K.L),발라드,18,4504,2001,113
358,32491274,아로하,조정석,발라드 국내드라마,1362,245265,2020,107
1235,3680,너를 위해,임재범,발라드,15,11306,2000,106
504,35945927,Ditto,NewJeans,댄스,3121,257135,2022,93
2240,35454426,Hype boy,NewJeans,댄스,2123,263943,2022,91
2020,30314784,밤편지,아이유,발라드,2461,455469,2017,88
498,36356993,I AM,IVE (아이브),댄스,2604,156948,2023,88
1281,8302,내게 오는 길,성시경,발라드,136,108198,2001,85
2243,35546497,After LIKE,IVE (아이브),댄스,3557,228833,2022,85
355,30190630,첫눈처럼 너에게 가겠다,에일리(Ailee),발라드 국내드라마,1104,350646,2017,84
1302,8290,처음처럼,성시경,발라드,31,8913,2001,84
520,35931532,Candy,NCT DREAM,댄스,7254,150716,2022,83
347,34657844,사랑인가 봐,멜로망스,발라드 국내드라마,259,185768,2022,81
506,35985167,OMG,NewJeans,댄스,1729,181001,2023,80
2228,34847378,LOVE DIVE,IVE (아이브),댄스,2737,235956,2022,79
2242,35454425,Attention,NewJeans,댄스,2592,223359,2022,79
359,8203900,너였다면,정승환,발라드 국내드라마,364,235012,2016,76
63,3890826,All For You,서인국,발라드,195,177250,2012,76

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6247 entries, 0 to 3844
Data columns (total 16 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   songId     6247 non-null   int64
 1   title      6247 non-null   object
 2   artist     6247 non-null   object
 3   genre      6245 non-null   object
 4   album      6247 non-null   object
 5   lyricist   5849 non-null   object
 6   composer   5845 non-null   object
 7   date       6247 non-null   object
 8   img        6247 non-null   object
 9   comment    6247 non-null   int64
 10  like       6247 non-null   object
 11  lyric      6242 non-null   object
 12  plylstSeq  6126 non-null   object
 13  year       6247 non-null   object
 14  p_list     6247 non-null   int64
 15  p_count    6247 non-null   int64
dtypes: int64(4), object(12)
memory usage: 829.7+ KB

In [82]:
import re

for i in df.like.values:
    if re.search('[^0-9]', str(i)):
        print(i)

총건수
											0

In [ ]:
df[df.like.str.contains('\t')][['songId', 'like']]

In [ ]:
df.like = df.like.astype(int)

In [ ]:
# 좋아요가 가장 많이 들어가 있는 곡은? 
# df.sort_values('like', ascending=False)[['songId', 'title', 'artist', 'genre', 'comment', 'like', 'year', 'p_count']].head(20)
df.sort_values('like')

In [4]:
df = pd.read_csv('data/melon_genre_ost_230527.csv')

In [5]:
df.head()

,songId,title,artist,genre,album,lyricist,composer,date,img,comment,like,lyric,plylstSeq
0,418168,희재,성시경,발라드 국내영화,국화꽃 향기 OST,양재선,MGR,20030201,https://cdnimg.melon.co.kr/cm/album/images/000...,332,138267,햇살은 우릴 위해 내리고 \r\n바람도 서롤 감싸게 했죠 \r\n우리 웃음속에 계절...,445029956 411111859
1,35609035,인생은 뷰티풀,김호중,발라드 국내영화,인생은 뷰티풀: 비타돌체,김호중,김호중,20220907,https://cdnimg.melon.co.kr/cm2/album/images/11...,197,17322,하나만 알고 둘은\r\n잘 모르는 사람입니다\r\n하루는 비틀거리고\r\n하루는 뒤...,457536944 474137187
2,1046278,서쪽 하늘,이승철,발라드 국내영화,청연 OST,이승철,윤명선,20051220,https://cdnimg.melon.co.kr/cm/album/images/003...,84,48109,서쪽하늘로 노을은 지고 \r\n이젠 슬픔이 돼버린 그대를 \r\n다시 부를수 없...,426571097 405285190
3,35609034,슬픈등,김호중,발라드 국내영화,인생은 뷰티풀: 비타돌체,김호중,김호중,20220907,https://cdnimg.melon.co.kr/cm2/album/images/11...,145,15389,누군가를 다시 만난다면\r\n여전히 나는 너를\r\n누군가를 다시 사랑하면\r\n영...,457536944 515278519
4,35728845,고백 (영화 '동감' X 츄 (이달의 소녀)),츄(Chuu),록/메탈 국내영화,고백 (영화 '동감' X 츄 (이달의 소녀)),강현민,강현민,20221016,https://cdnimg.melon.co.kr/cm2/album/images/11...,80,16902,말해야 하는데 네 앞에 서면\r\n아무 말 못 하는 내가 미워져\r\n용기를 내야 ...,484732185 513801514

In [6]:
df.lyric = df.lyric.str.replace('\r', '')

In [7]:
df.head()

,songId,title,artist,genre,album,lyricist,composer,date,img,comment,like,lyric,plylstSeq
0,418168,희재,성시경,발라드 국내영화,국화꽃 향기 OST,양재선,MGR,20030201,https://cdnimg.melon.co.kr/cm/album/images/000...,332,138267,햇살은 우릴 위해 내리고 \n바람도 서롤 감싸게 했죠 \n우리 웃음속에 계절은 오고...,445029956 411111859
1,35609035,인생은 뷰티풀,김호중,발라드 국내영화,인생은 뷰티풀: 비타돌체,김호중,김호중,20220907,https://cdnimg.melon.co.kr/cm2/album/images/11...,197,17322,하나만 알고 둘은\n잘 모르는 사람입니다\n하루는 비틀거리고\n하루는 뒤뚱거리고\n...,457536944 474137187
2,1046278,서쪽 하늘,이승철,발라드 국내영화,청연 OST,이승철,윤명선,20051220,https://cdnimg.melon.co.kr/cm/album/images/003...,84,48109,서쪽하늘로 노을은 지고 \n이젠 슬픔이 돼버린 그대를 \n다시 부를수 없을 것 ...,426571097 405285190
3,35609034,슬픈등,김호중,발라드 국내영화,인생은 뷰티풀: 비타돌체,김호중,김호중,20220907,https://cdnimg.melon.co.kr/cm2/album/images/11...,145,15389,누군가를 다시 만난다면\n여전히 나는 너를\n누군가를 다시 사랑하면\n영원히 나는 ...,457536944 515278519
4,35728845,고백 (영화 '동감' X 츄 (이달의 소녀)),츄(Chuu),록/메탈 국내영화,고백 (영화 '동감' X 츄 (이달의 소녀)),강현민,강현민,20221016,https://cdnimg.melon.co.kr/cm2/album/images/11...,80,16902,말해야 하는데 네 앞에 서면\n아무 말 못 하는 내가 미워져\n용기를 내야 해 후회...,484732185 513801514